export const swiperDummy = [
  { id: 1, title: "1번이미지", img: "/images/swiperImage.jpeg" },
  { id: 2, title: "2번이미지", img: "/images/tai.jpg" },
  { id: 3, title: "3번이미지", img: "/images/swiperImage.jpeg" },
  { id: 4, title: "4번이미지", img: "/images/swiperImage.jpeg" },
];

export const totalTop = [
  {
    id: 1,
    title: "전지적 독자 시점",
    genre: "판타지",
    author: "UMI",
    star: 4.5,
    review: 5432,
    img: "/images/전지적독자시점.PNG",
  },
  {
    id: 2,
    title: "마음의 소리",
    genre: "개그",
    author: "조석",
    star: 4.4,
    review: 4321,
    img: "/images/마음의 소리.PNG",
  },
  {
    id: 3,
    title: "재벌집 막내아들",
    genre: "드라마",
    author: "JP",
    star: 4.3,
    review: 3215,
    img: "/images/재벌집막내.PNG",
  },
  {
    id: 4,
    title: "우렉 마지노",
    genre: "판타지",
    author: "SIU",
    star: 4.2,
    review: 2154,
    img: "/images/우렉마지노.PNG",
  },
  {
    id: 5,
    title: "호랑이형님",
    genre: "판타지",
    author: "이상규",
    star: 4.1,
    review: 1543,
    img: "/images/호랑이형님.PNG",
  },
];

export const reviewTop = [
  {
    id: 1,
    title: "호랑이형님",
    genre: "판타지",
    author: "이상규",
    star: 4.1,
    review: 1543,
    img: "/images/호랑이형님.PNG",
  },
  {
    id: 2,
    title: "우렉 마지노",
    genre: "판타지",
    author: "SIU",
    star: 4.2,
    review: 2154,
    img: "/images/우렉마지노.PNG",
  },
  {
    id: 3,
    title: "재벌집 막내아들",
    genre: "드라마",
    author: "JP",
    star: 4.3,
    review: 3215,
    img: "/images/재벌집막내.PNG",
  },
  {
    id: 4,
    title: "마음의 소리",
    genre: "개그",
    author: "조석",
    star: 4.4,
    review: 4321,
    img: "/images/마음의 소리.PNG",
  },
  {
    id: 5,
    title: "전지적 독자 시점",
    genre: "판타지",
    author: "UMI",
    star: 4.5,
    review: 5432,
    img: "/images/전지적독자시점.PNG",
  },
];

export const recentReview = [
  {
    id: 1,
    name: "장난꾸러기",
    img: "/svg/profile.png",
    star: 5,
    content:
      "두번 정주행한 작품. 정신 나간 주인공의 정신 나간 여정과 주변에 있는 정신 나간 놈들이 어우러져 정신 나간 작품이 탄생했다. 글이 참 맛깔난다.",
    title: "호랑이형님",
    author: "이상규",
  },
  {
    id: 2,
    name: "장난꾸러기",
    img: "/svg/profile.png",
    star: 5,
    content:
      "두번 정주행한 작품. 정신 나간 주인공의 정신 나간 여정과 주변에 있는 정신 나간 놈들이 어우러져 정신 나간 작품이 탄생했다. 글이 참 맛깔난다.",
    title: "호랑이형님",
    author: "이상규",
  },
  {
    id: 3,
    name: "장난꾸러기",
    img: "/svg/profile.png",
    star: 5,
    content:
      "두번 정주행한 작품. 정신 나간 주인공의 정신 나간 여정과 주변에 있는 정신 나간 놈들이 어우러져 정신 나간 작품이 탄생했다. 글이 참 맛깔난다.",
    title: "호랑이형님",
    author: "이상규",
  },
  {
    id: 4,
    name: "장난꾸러기",
    img: "/svg/profile.png",
    star: 5,
    content:
      "두번 정주행한 작품. 정신 나간 주인공의 정신 나간 여정과 주변에 있는 정신 나간 놈들이 어우러져 정신 나간 작품이 탄생했다. 글이 참 맛깔난다.",
    title: "호랑이형님",
    author: "이상규",
  },
];

export const totalWebToon = [
  {
    id: 1,
    title: "전지적 독자 시점",
    genre: "판타지",
    author: "UMI",
    star: 4.5,
    review: 5432,
    img: "/images/전지적독자시점.PNG",
  },
  {
    id: 2,
    title: "마음의 소리",
    genre: "개그",
    author: "조석",
    star: 4.4,
    review: 4321,
    img: "/images/마음의 소리.PNG",
  },
  {
    id: 3,
    title: "재벌집 막내아들",
    genre: "드라마",
    author: "JP",
    star: 4.3,
    review: 3215,
    img: "/images/재벌집막내.PNG",
  },
  {
    id: 4,
    title: "우렉 마지노",
    genre: "판타지",
    author: "SIU",
    star: 4.2,
    review: 2154,
    img: "/images/우렉마지노.PNG",
  },
  {
    id: 5,
    title: "호랑이형님",
    genre: "판타지",
    author: "이상규",
    star: 4.1,
    review: 1543,
    img: "/images/호랑이형님.PNG",
  },
  {
    id: 6,
    title: "호랑이형님",
    genre: "판타지",
    author: "이상규",
    star: 4.1,
    review: 1543,
    img: "/images/호랑이형님.PNG",
  },
  {
    id: 7,
    title: "호랑이형님",
    genre: "판타지",
    author: "이상규",
    star: 4.1,
    review: 1543,
    img: "/images/호랑이형님.PNG",
  },
  {
    id: 8,
    title: "호랑이형님",
    genre: "판타지",
    author: "이상규",
    star: 4.1,
    review: 1543,
    img: "/images/호랑이형님.PNG",
  },
  {
    id: 9,
    title: "호랑이형님",
    genre: "판타지",
    author: "이상규",
    star: 4.1,
    review: 1543,
    img: "/images/호랑이형님.PNG",
  },
  {
    id: 10,
    title: "호랑이형님",
    genre: "판타지",
    author: "이상규",
    star: 4.1,
    review: 1543,
    img: "/images/호랑이형님.PNG",
  },
  {
    id: 11,
    title: "호랑이형님",
    genre: "판타지",
    author: "이상규",
    star: 4.1,
    review: 1543,
    img: "/images/호랑이형님.PNG",
  },
  {
    id: 12,
    title: "호랑이형님",
    genre: "판타지",
    author: "이상규",
    star: 4.1,
    review: 1543,
    img: "/images/호랑이형님.PNG",
  },
  {
    id: 13,
    title: "호랑이형님",
    genre: "판타지",
    author: "이상규",
    star: 4.1,
    review: 1543,
    img: "/images/호랑이형님.PNG",
  },
  {
    id: 14,
    title: "호랑이형님",
    genre: "판타지",
    author: "이상규",
    star: 4.1,
    review: 1543,
    img: "/images/호랑이형님.PNG",
  },
  {
    id: 15,
    title: "호랑이형님",
    genre: "판타지",
    author: "이상규",
    star: 4.1,
    review: 1543,
    img: "/images/호랑이형님.PNG",
  },
];

export const series = {
  id: 1,
  title: "마음의 소리",
  img: "/images/마음의 소리.PNG",
  genre: "개그",
  author: "조석",
  status: "완결",
  description:
    "자그마치 637일을 기다린 남자 친구 덕구가제대 기념, 여행 온 해안가에서 고백했다.“나 다, 다른 여자랑 잤어.”죽일까? 묻을까? 팰까?여름은 고민 끝에 오싹한 결심을 했다.그리고 새벽 두 시.여름은 거나하게 술에 취한 채 그에게 전화하여 진상 짓을 펼친다.그런데 왜, 오늘따라 덕구 목소리가 듣기 좋지?―덕구 변성기 왔니?왜긴. 자다가 봉변당한 생면부지의 남자, 도하니까!한여름 밤, 우연한 통화로 시작된 여름과 도하의 기상천외한 로맨스!도하는 어쩌다 첫 만남에서 여름의 어깨를 끌어안게 됐을까?[일러스트] 감몬[로고 및 표지 디자인] 어나더",
  star: 4.35,
  review: 10,
};
